### PR TITLE
Fix #107: Handle typedef of opaque structs.

### LINKED ISSUE #107: Handle typedef of opaque structs
When an opaque struct is defined in a C header like that:
```c
    typedef struct foo foo;
```
no symbols are generated in the .d file. It only works if the name of the struct is not the same as the typedef. The output should be:
```d
   struct foo;
```

### PR DESCRIPTION
**Pull request by ciechowoj**
As in the header.

### CODE REVIEW

**Comment by jacob-carlborg** [comment]
👌

**Comment by jacob-carlborg** [comment]
Thanks.

**Comment by ciechowoj** [comment]
Eh, it seems that my fix the issue, but adds adds another regression. I had forgotten that there is no struct forward declarations in D, so that following code will no compile:

```
struct A;
struct A { int b; }
```

I think the correct implementation should omit the first declaration if the second one is present. I'll fix when I have some spare time.

**Comment by jacob-carlborg** [comment]
Should I revert?

**Comment by ciechowoj** [comment]
Maybe wait a moment, let say 4h from now, I'm trying to fix it.

**Comment by jacob-carlborg** [comment]
Ok, no problem.

**Pull request merged**
