### PR TITLE
Two minor array binding fixes

### PR DESCRIPTION
**Pull request by Dicebot**
First commit fixes root issue behind #26
Second ensures that #35 actually works (it seemed working but
bug is still open)

### CODE REVIEW

**Comment by jacob-carlborg** [comment]
Tests are failing.

**Comment by mihails-strasuns-sociomantic** [comment]
Yep, checking travis output.

**Comment by mihails-strasuns-sociomantic** [comment]
Oh looks like it produced a different AST in clang 3.1:

```
Testing with libclang version 3.1
...
    +extern __gshared <unimplemented> sys_errlist;
```

Is there a way to query libclang version from the bindings?

**Comment by jacob-carlborg** [comment]
> Is there a way to query libclang version from the bindings?

There's [clang_getClangVersion](http://clang.llvm.org/doxygen/group__CINDEX__MISC.html#ga307e960e9dccaf721c0032cd4edd8908).

**Comment by mihails-strasuns-sociomantic** [comment]
Thanks. I'll abuse the CI a bit to get necessary debugging info.

**Comment by mihails-strasuns-sociomantic** [comment]
Nasty. It says `CXType_Unexposed` for extern static array types in old clang and doesn't even parse it as valid declaration. I'll try finding a workaround but it may be a dead end. Are there version-based exceptions in your test system?

**Comment by mihails-strasuns-sociomantic** [comment]
Yep, for clang 3.3 and before type of such variable is completely unknown from a cursor - `CXType_Unexposed`, empty `spelling` string, attempts to force `ArrayType` result in invalid element type and -1 size.

@jacob-carlborg waiting for your call on this.

**Comment by jacob-carlborg** [comment]
So you're basically saying that this can' work for Clang 3.3 and before?

**Comment by mihails-strasuns-sociomantic** [comment]
Yes, at least it is beyond my libclang knowledge (have no idea what to do if parser procuded cursor is missing required information). Still, making it work for 3.4+ is better than keeping it broken completely ;)

**Comment by jacob-carlborg** [comment]
Ok, I guess we can drop support for 3.3 and before. Could you please create a separate commit for that explaining the reason in the commit message. Remove the versions from the test and update the readme.

**Comment by mihails-strasuns-sociomantic** [comment]
Ok, green now. NB: some OS/platform combinations now have empty clang version array - you may want to add some new tested versions there.

**Comment by jacob-carlborg** [comment]
:ok_hand:

**Comment by jacob-carlborg** [comment]
Thanks.

**Comment by mihails-strasuns-sociomantic** [comment]
Thanks!

**Pull request merged**
