### PR TITLE
Fix issue98.

### PR DESCRIPTION
**Pull request by ciechowoj**
As in the title.

### CODE REVIEW

**Comment by ciechowoj** [comment]
Btw. how can I switch clang to 3.9?

**Comment by jacob-carlborg** [comment]
Just add the necessary links to this method https://github.com/jacob-carlborg/dstep/blob/master/test.d#L274

**Comment by ciechowoj** [comment]
Is it going to use the most recent one?

**Comment by ciechowoj** [comment]
Does it need to support the older versions as well? If you are going to bump the minimal required version to 3.9 should I remove all older links?

**Comment by jacob-carlborg** [comment]
The idea is to support the current version and the previous version of libclang. Currently that would mean 3.9 and 4.0.

**Comment by jacob-carlborg** [comment]
You can remove the older versions. I don't think the tests would pass otherwise.

**Comment by ciechowoj** [comment]
I see, I don't have time to update those links today, I'll do it on the week, or the next weekend.

**Comment by jacob-carlborg** [comment]
Ideally the libclang bindings should be updated to 4.0 as well.

**Comment by ciechowoj** [comment]
Sure.

**Comment by jacob-carlborg** [comment]
I've made some changes in master that should help you:

* Bumped the min requirements to libclang 3.8
* Cleaned up the old versions of libclang in `test.d`
* Updated to Ubuntu 14.04 in Travis CI
* Updated the Clang bindings and internal headers to version 4.0.0

**Comment by ciechowoj** [comment]
I updated the links but something is wrong with windows build. I investigate on other occasion...

**Comment by ciechowoj** [comment]
The problem seems to be in the linker flags:

            "lflags-windows-x86": ["/LIBPATH:C:\\PROGRA~2\\LLVM\\lib", "libclang.lib", "Ole32.lib"],
            "lflags-windows-x86_64": ["/LIBPATH:C:\\PROGRA~1\\LLVM\\lib", "libclang.lib", "Ole32.lib"],

It tries to find them in program files, when it should look into downloaded clang directory.

**Comment by ciechowoj** [comment]
AppVeyor green : )

**Comment by jacob-carlborg** [comment]
How did this work before with `libclang.lib`?

**Comment by ciechowoj** [comment]
Ill need to check but maybe there is preinstalled x64 LLVM in AppVeyor?

**Comment by jacob-carlborg** [comment]
The code changes look good, but the commits can be slightly improved.

* Squash all commits except the changelog commit
* Please start the commit message with `Fix #98: ...`, then GitHub will automatically close the issue
* Please flesh out the commit message, with title of the issue and also mention that the minimum requirement of libclang is now 3.9.0
* Update the readme as well, which also mentions the minimum requirement of libclang

**Comment by jacob-carlborg** [comment]
> Ill need to check but maybe there is preinstalled x64 LLVM in AppVeyor?

I would say that's unlikely. But way did both 32 and 64bit work before, but now (before your fix) 32bit did not work? Just curious why it worked before and perhaps that the test setup was not correct before.

**Comment by ciechowoj** [comment]
> I would say that's unlikely. 

If you had you would have been wrong : ) :

```
Build started
git clone -q https://github.com/jacob-carlborg/dstep.git C:\projects\dstep
git fetch -q origin +refs/pull/161/merge:
git checkout -qf FETCH_HEAD
Running Install scripts
echo dummy install script - dont remove me
dummy install script - dont remove me
echo dummy build script - dont remove me
dummy build script - dont remove me
powershell -NoProfile -File appveyor.ps1 < NUL
    Directory: C:\Program Files\LLVM\bin
Mode                LastWriteTime         Length Name                          
----                -------------         ------ ----                          
-a----         3/9/2017   6:45 PM       67564032 clang++.exe                   
-a----         3/9/2017   6:33 PM        2570240 clang-apply-replacements.exe  
-a----         3/9/2017   6:35 PM       19074048 clang-change-namespace.exe    
-a----         3/9/2017   6:33 PM       55822848 clang-check.exe               
-a----         3/9/2017   6:45 PM       67564032 clang-cl.exe                  
-a----         3/9/2017   6:45 PM       67564032 clang-cpp.exe                 
-a----         3/9/2017   6:33 PM        2597888 clang-format.exe              
-a----         3/9/2017   6:32 PM       22418432 clang-import-test.exe         
-a----         3/9/2017   6:35 PM       18804736 clang-include-fixer.exe       
-a----         3/9/2017   6:32 PM        3426816 clang-offload-bundler.exe     
-a----         3/9/2017   6:35 PM       19681280 clang-query.exe               
-a----         3/9/2017   6:33 PM       18998784 clang-rename.exe              
-a----         3/9/2017   6:33 PM       18717184 clang-reorder-fields.exe      
-a----         3/9/2017   6:35 PM       24540672 clang-tidy.exe                
-a----         3/9/2017   6:33 PM       67564032 clang.exe                     
-a----         3/9/2017   6:35 PM       18864128 find-all-symbols.exe          
-a----        11/8/2016   5:50 AM          20626 git-clang-format              
-a----         3/9/2017   6:45 PM       46529024 ld.lld.exe                    
-a----         3/9/2017   6:36 PM       59555840 libclang.dll                  
-a----         3/9/2017   6:45 PM         610816 libiomp5md.dll                
-a----         3/9/2017   6:27 PM         610816 libomp.dll                    
-a----         3/9/2017   6:45 PM       46529024 lld-link.exe                  
-a----         3/9/2017   6:35 PM       46529024 lld.exe                       
-a----         3/9/2017   6:28 PM       15597056 llvm-ar.exe                   
-a----         3/9/2017   6:45 PM       15597056 llvm-lib.exe                  
-a----         3/9/2017   6:35 PM       15872512 llvm-objdump.exe              
-a----         3/9/2017   6:45 PM       15597056 llvm-ranlib.exe               
-a----         3/9/2017   6:28 PM       43993600 LTO.dll                       
-a----         3/9/2017   6:33 PM       18244096 modularize.exe                
-a----       11/13/2015   8:34 PM             23 scan-build.bat                
-a----       12/21/2015  12:19 PM           4504 scan-view                     
    Directory: C:\Program Files\LLVM\lib
Mode                LastWriteTime         Length Name                          
----                -------------         ------ ----                          
d-----        3/16/2017   4:52 AM                clang                         
-a----         3/9/2017   6:35 PM          91906 libclang.lib                  
-a----         3/9/2017   6:45 PM         153636 libiomp5md.dll                
-a----         3/9/2017   6:27 PM         153636 libomp.lib                    
-a----         3/9/2017   6:27 PM        1540680 lldCOFF.lib                   
-a----         3/9/2017   6:27 PM          15580 lldConfig.lib                 
-a----         3/9/2017   6:27 PM         369596 lldCore.lib                   
-a----         3/9/2017   6:27 PM         266392 lldDriver.lib                 
-a----         3/9/2017   6:34 PM        7631266 lldELF.lib                    
-a----         3/9/2017   6:27 PM        2263638 lldMachO.lib                  
-a----         3/9/2017   6:27 PM         109180 lldReaderWriter.lib           
-a----         3/9/2017   6:27 PM         258566 lldYAML.lib                   
    Directory: C:\Program Files\LLVM\include
Mode                LastWriteTime         Length Name                          
----                -------------         ------ ----                          
d-----        3/16/2017   4:52 AM                clang-c                       
d-----        3/16/2017   4:52 AM                llvm-c
```
https://ci.appveyor.com/project/jacob-carlborg/dstep/build/1.0.362/job/vgk9g127u9lffi1l

And for x86 it was installed by our script:
```
1 | 2 | 3
-- | -- | --
-if ($env:arch -eq "x86") { |   |  
  | -  echo "Downloading 32-bit LLVM..."; |   |  
  | -  Invoke-WebRequest http://llvm.org/releases/3.8.1/LLVM-3.8.1-win32.exe -OutFile c:\LLVM.exe; |   |  
  | -  7z x c:\LLVM.exe -oc:\PROGRA~2\LLVM > $null; |   |  
  | -}
```

**Comment by jacob-carlborg** [comment]
Oh 😮, I see. I didn't expect that.

**Comment by jacob-carlborg** [comment]
Thanks for all the help 👍.

**Pull request merged**
