### PR TITLE
Provide D1 fallback for new alias syntax

### PR DESCRIPTION
**Pull request by mihails-strasuns-sociomantic**
Fixup for new syntax changes

Rebase of https://github.com/jacob-carlborg/dstep/pull/125 under work account to ensure better reaction time ;)

### CODE REVIEW

**Comment by jacob-carlborg** [comment]
> Rebase of #125 under work account to ensure better reaction time ;)

There won't be any difference in reaction time :). But know it just looks odd with different accounts for the author and committer.

**Comment by jacob-carlborg** [comment]
👌

**Comment by mihails-strasuns-sociomantic** [comment]
> There won't be any difference in reaction time

_my_ reaction time ;) - I don't check my personal github account often lately

**Comment by jacob-carlborg** [comment]
Ah, I see :)

**Pull request merged**
