### PR TITLE
Fix #204: C INT_MAX not handled.

### LINKED ISSUE #204: C INT_MAX not handled
Using DStep v0.2.3-16-g1308991 compiled on Debian Sid with LDC 1.11.0 and LLVM 6.0, I generated a module for fontconfig.h (version 2.13.0). Sadly:
```
generated/fontconfig.d(257): Error: undefined identifier INT_MAX
generated/fontconfig.d(576): Error: undefined identifier stat_
```
I am not sure where the `stat_` is creeping in. The generated D is:
```d
FcCache* FcDirCacheLoadFile (const(FcChar8)* cache_file, stat_* file_stat);
```

### PR DESCRIPTION
**Pull request by ciechowoj**

### CODE REVIEW

**Comment by ciechowoj** [comment]
I think testing on dmd-nightly is a bit overkill:
image

**Comment by ciechowoj** [comment]
Thats my point. No reason to test against unstable builds...

**Comment by ciechowoj** [comment]
I know, but still I guess the CI in nightly build is more prone to be broken and the gain from having tests for nightly is quite minor...

**Comment by jacob-carlborg** [comment]
I can update the configuration to allow it to fail.

**Comment by ciechowoj** [comment]
Yeah, I think it would make sense.

**Comment by ZombineDev** [comment]
What's down is the server serving the dmd nightly archives. It's equally like that the server serving the official releases would go down and the nightlies sever would remain up.

**Comment by ciechowoj** [comment]
Whatever, still it increases the probability that the tests are broken for no good reason...

**Comment by jacob-carlborg** [comment]
The reason the I want to test that nightlies is that I've been burned before by regressions that weren't noticed until the final release was out. There was a time when every single release broke at least one of my project due to a regression. It's better now but still.

**Comment by ciechowoj** [comment]
I see, I didn't know that it was that bad. Still, I don't know how long is it broken, if the build/server is broken very often then is makes no sense to have this tests...

**Comment by jacob-carlborg** [comment]
I'm waiting for: https://travis-ci.org/jacob-carlborg/dstep/builds/435326643.

**Comment by jacob-carlborg** [comment]
The nightly is now allowed to fail. Perhaps if you try and rebase this PR.

**Comment by ciechowoj** [comment]
@jacob-carlborg 
What about merging this PR?

**Comment by jacob-carlborg** [comment]
> What about merging this PR?

There's a conflict now. Most likely because I just merged the other PR you pinged about.

**Comment by ciechowoj** [comment]
Rebased.

**Comment by jacob-carlborg** [comment]
> Rebased.

Thanks. Waiting for the tests.

**Pull request merged**
