### PR TITLE
Fix #138: Repeated declarations cause problems.

### LINKED ISSUE #138: Repeated declarations cause problems
In /usr/include/libdvbv5/dvb-fe.h there are two instances of:
```
extern const unsigned fe_bandwidth_name[8];
```
in the C (and C++) header files this is not a problem (though I am going to report this as a bug). This leads to two lines:
```
extern __gshared const(uint)[8] fe_bandwidth_name;
```
in the generated by DStep dvb_fe.d. Sadly this leads to compilation errors:
```
generated/dvb_fe.d(782): Error: variable dvb_fe.fe_bandwidth_name conflicts with variable dvb_fe.fe_bandwidth_name at generated/dvb_fe.d(775)
```
Is this a bug in DStep or a bug in ldc2?

### PR DESCRIPTION
**Pull request by ciechowoj**
As in the title.

### CODE REVIEW

**Comment by jacob-carlborg** [comment]
"case problems" is not very clear or descriptive 😃. Could you please update the commit with something more descriptive, i.e. that duplicated symbols are ignored/skipped.

**Comment by ciechowoj** [comment]
Better? : ) Usually I just copy the tittle of corresponding issue...

**Comment by jacob-carlborg** [comment]
> Usually I just copy the tittle of corresponding issue...

The title of the issue might not always be correct.

**Comment by jacob-carlborg** [comment]
👌

**Comment by jacob-carlborg** [comment]
Thanks.

**Pull request merged**
