### PR TITLE
Updated alias syntax

### PR DESCRIPTION
**Pull request by biozic**
The same alias syntax (the new one) is now used everywhere.

### CODE REVIEW

**Comment by jacob-carlborg** [comment]
Could you please slightly improve the commit message.

**Comment by jacob-carlborg** [comment]
LGTM. @Dicebot @ciechowoj what do you think?

**Comment by biozic** [comment]
Is "Use new alias syntax everywhere" better?

**Comment by jacob-carlborg** [comment]
> Is "Use new alias syntax everywhere" better?

Yes, but perhaps even better, something like: "Use new alias syntax for output result". I would like to emphasize that new alias syntax is used in the translated code and not the DStep code itself.

**Comment by ciechowoj** [comment]
> LGTM. @Dicebot @ciechowoj what do you think?

Yeah, I always wanted to change this.

**Comment by biozic** [comment]
@Dicebot I wasn't aware that D1 was supposed to be supported. Does this also include [enum aliases](https://github.com/jacob-carlborg/dstep/blob/master/dstep/translator/Enum.d#L42), which already used the new syntax?

**Comment by jacob-carlborg** [comment]
I know there were some issues with the new alias syntax and `extern (C)`, something like:

```d
extern (C) alias Callback = void function();
```

Has that been fixed? Or perhaps it doesn't matter when `extern (C):` will be at the top?

**Comment by biozic** [comment]
All of these seem to work (2.070.2):
```d
alias Callback = extern (C) void function();
extern (C) alias Callback = void function();
alias extern (C) void function() Callback;
extern (C) alias void function() Callback;
```

**Comment by jacob-carlborg** [comment]
@biozic could you please update the changelog as well.

**Comment by jacob-carlborg** [comment]
👌

**Comment by jacob-carlborg** [comment]
Thanks. Next time, write a comment after a change. I don't get notification just for changes.

**Comment by jacob-carlborg** [comment]
@biozic I just merged this and now the tests are failing: https://travis-ci.org/jacob-carlborg/dstep/jobs/201110273

**Comment by ciechowoj** [comment]
Yes, I've just noticed it also. What is more AppVeyor reports that the tests are passing despite the fact they are failing.

**Comment by biozic** [comment]
The failing tests are tests that were added after my PR, so I guess the CI is not faulty. I will submit a PR to fix the newly-added failing tests.

**Comment by jacob-carlborg** [comment]
Fair enough. Waiting for the tests in the new PR.

**Pull request merged**
